### ISSUE TITLE
Add a screenshot of opensea profile with nfts

### ISSUE THREAD

**Issue by aakzsh** [GDSC-USICT/gdsc-card#3]
Add a screenshot in readme file that shows the opensea account of gdsc with few or all nft profiles, whatever looks nicer.

**Comment by shubhsardana29** [comment]
I would like to work on this issue, please assign it to me. @aakzsh

**Comment by aakzsh** [comment]
done

**Comment by shubhsardana29** [comment]
please check the pr @aakzsh

**Comment by aakzsh** [comment]
#6
